### ISSUE TITLE
t - Time to experiation in years

### ISSUE THREAD

**Issue by zheoreh** [MattL922/implied-volatility#2]
Can you explain that parameter? In your expamle this value is  .1

I calculate this value so ((new Date(date)).getTime() - (new Date).getTime()) / 86400000 / 365

but in this case I get wron volatility, for example equal to 1,64, more than 1 (100%)

If I calculate this value so ((new Date(date)).getTime() - (new Date).getTime()) / 86400000 / 365 \* 100 then I get more correct value of volatility, but anyway this value does not equal to volatility from http://finance.yahoo.com/q/op?s=AAPL+Options

How to calculate the volatility?

For example I have next data:
Symbol: AAPL, Exp: 7/31/2015, Call, Strike: 105

I passed next parameters to getImpliedVolatility(expectedCost, s, k, t, r, callPut, estimate)
18.3 123.575 105 0.8860913146879756 0.05 "Calls"

And have got such result as 0.6890625 but in yahoo volatility is 71.48%

**Comment by MattL922** [comment]
The 't' parameter is the time until expiration measured in years.  This is going to differ for each person depending on how they define a year.  A calendar year is usually 365 days, but only about 252 of those are trading days.  It's a matter of preference which value you decide to use.  This has the side effect of producing a different volatility measurement than someone using a different value.

Yahoo finance might use a different value than you are, resulting in differing volatilities.  Yahoo finance is also delayed a little bit so it isn't showing real time data.

I'm not sure I understand your initial formula.  It looks like you're calculating a time delta in milliseconds, then dividing by 86400000 to convert to days, then dividing by 365 to get years.  This looks right, but I'm not sure how multiplying by 100 gave you a more accurate answer.  Multiplying by 100 will just convert from a decimal to a percent.

You might also not want to play too much with the 'estimate' parameter.  Using numbers that are too large or too small can cause the algorithm to diverge and produce an incorrect volatility.  The algorithm is essentially just a binary search type of guess and check.

Your last calculation looks right though.  Yahoo probably just uses a different denominator to calculate 't' as mentioned above.  Also, are you sure about your risk-free interest rate?  Five percent seems kind of high.  I think a one year US government bond is going for about a quarter of a percent right now.

**Comment by nirajmit** [comment]
I would just write a simple test case which iterate through all options of a given ticker (user specified ) and displays yahoo vol and our calculated vol - let's see how different the number is
